Fix Issue #45 - Multiple familes in ped file
denovogear/denovogear pull request #196
Opened 2016-10-04 22:54 UTC by stevenhwu

- Merge family ID and individual ID in `ped.h` to make id unique. Use an "unique/unusual/obscure" delimiter, `_F@I_`, to concatenate these two IDs, then everything will be unique in `table_`. The `id()` function take care of the rest.
  - A simple delimiter (`_`, `@` ...etc) is avoid to prevent the case that family name is something like `*f1@` or `*f1_`.
- Update related unittests.

=============================================

Let's assume we have a pedigree looks like the following

```
1       1       0       0       1       NA12891
1       2       0       0       2       NA12892
1       3       1       2       2       NA12878
2       1       0       0       1       NA12900
2       2       0       0       2       NA12901
2       3       1       2       1       NA12902
```
In `ped.h` the `Parse()` function.

The first part relate to `string_table`, we append family id and individual id together in the `child_names` (instead of just individual id). It should looks something like
```
1_F@I_1
1_F@I_2
1_F@I_2
2_F@I_1
2_F@I_2
2_F@I_3
```

We pick a pretty "unique/unusual/obscure" delimiter, in this case `_F@I_`, where `_F` is the suffix for family and `I_` is the prefix for individual. A simple "\_" or "@" is avoid to prevent the case that family name is something like `*f1@` or `*f1_`.

The delimiter can be update at `const std::string FAM_IND_DELIM = "_F@I_";`

The second part, where we parse it to `table_` with struct `Member` where everything is `size_t`. The `id()` function automatically take care of that due to the way `child_names` in constructed.

The new output looks like
```
##PEDIGREE=<ID=LB-NA12878:Solexa-135852,Father=GL-1_F@I_1,Mother=GL-1_F@I_2,FatherMR=3.0e-08,MotherMR=3.0e-08>
##PEDIGREE=<ID=LB-NA12891:Solexa-135851,Original=GL-1_F@I_1,OriginalMR=2.0e-08>
##PEDIGREE=<ID=LB-NA12892:Solexa-135853,Original=GL-1_F@I_2,OriginalMR=2.0e-08>
##PEDIGREE=<ID=LB-NA12900:L900,Original=GL-2_F@I_1,OriginalMR=2.0e-08>
##PEDIGREE=<ID=LB-NA12901:L901,Original=GL-2_F@I_2,OriginalMR=2.0e-08>
##PEDIGREE=<ID=LB-NA12902:L902,Father=GL-2_F@I_1,Mother=GL-2_F@I_2,FatherMR=3.0e-08,MotherMR=3.0e-08>
```

2016-10-04 23:52 UTC, reedacartwright commented
Jenkins, okay to test.

--
Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute
Arizona State University
==================
Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign A-224A, 1-480-965-9949
Website: http://cartwrig.ht/

On Tue, Oct 4, 2016 at 3:54 PM, Jenkins Bot <notifications@github.com>
wrote:

> Can one of the admins verify this patch?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/denovogear/denovogear/pull/196#issuecomment-251537119>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAGOHlpBVxOZ_WZZRSPzIzFwpXDZcT1uks5qwtk4gaJpZM4KOP6f>
> .
>

2016-10-04 23:53 UTC, reedacartwright commented
I would use probably use '\t' as an internal separator since fields cannot
contain a tab.

--
Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute
Arizona State University
==================
Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign A-224A, 1-480-965-9949
Website: http://cartwrig.ht/

On Tue, Oct 4, 2016 at 4:52 PM, Reed A. Cartwright <cartwright@asu.edu>
wrote:

> Jenkins, okay to test.
>
> --
> Reed A. Cartwright, PhD
> Barrett Honors Faculty
> Assistant Professor of Genomics, Evolution, and Bioinformatics
> School of Life Sciences
> Human and Comparative Genomics Laboratory
> The Biodesign Institute
> Arizona State University
> ==================
> Availability: http://links.asu.edu/CartwrightCalendar
> Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
> Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
> 85287-5301 USA
> Office: Biodesign A-224A, 1-480-965-9949
> Website: http://cartwrig.ht/
>
> On Tue, Oct 4, 2016 at 3:54 PM, Jenkins Bot <notifications@github.com>
> wrote:
>
>> Can one of the admins verify this patch?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/denovogear/denovogear/pull/196#issuecomment-251537119>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AAGOHlpBVxOZ_WZZRSPzIzFwpXDZcT1uks5qwtk4gaJpZM4KOP6f>
>> .
>>
>
>

2016-10-05 00:01 UTC, stevenhwu commented
Then the output in vcf will look something like
```
##PEDIGREE=<ID=LB-NA12892:Solexa-135853,Original=GL-1  2,OriginalMR=2.0e-08>
                                                     ^^
##PEDIGREE=<ID=LB-NA12900:L900,Original=GL-2    1,OriginalMR=2.0e-08>
                                            ^^^^ each line will have different amount of spaces
```
Which might make `BamTest.cmake.in` hard to create.

OR we can parse internally with `\t`, then output to vcf with something other than `\t`

2016-10-05 00:04 UTC, stevenhwu commented
btw, can someone explain the coverage report please? @reedacartwright @anderspitman 
I really expect the delta is 0% here.
```
Current coverage is 65.36% (diff: 100%)

>Merging #196 into develop will increase coverage by 8.18%
```

2016-10-13 02:04 UTC, reedacartwright requested changes
Are we using the slash to join the library and the sample name as well?

2016-10-13 02:04 UTC, reedacartwright commented on Tests/Unit/dng/find_mutation.cc
> +    BOOST_CHECK_EQUAL("LB/NA12878:Solexa-135852", mutation_stats.dnl);
Looks like running `dng-call` on a vcf still assumes that names are "sample:library" instead of "sample/library".

Can we fix that in this PR too?

2016-10-13 02:04 UTC, reedacartwright commented on src/include/dng/io/ped.h
> +    std::size_t id(const std::string &name, NameContainer &names) const {
static function, right?

2016-10-13 02:04 UTC, reedacartwright commented on src/include/dng/io/ped.h
> +        bool is_individual_id_not_unique = false;
Add a TODO here for me to look at later. I want to think about this algorithm.

2016-10-13 02:04 UTC, reedacartwright commented on src/include/dng/io/ped.h
> +                    ParseGender(string_table[nrow][4]),
sex

2016-10-13 02:04 UTC, reedacartwright commented on src/lib/newick.cc
> +#define DNG_SM_PREFIX "SM/" // define also in relationship_graph.cc
Is there a good way we can move these definitions to a common header file?

2016-10-13 02:04 UTC, reedacartwright commented on src/lib/relationship_graph.cc
> +#define DNG_LB_PREFIX "LB/"
Can we move these to a header file? So we can keep newick.cc in sync with relationship_graph?

2016-10-13 06:01 UTC, stevenhwu commented on Tests/Unit/dng/find_mutation.cc
> +    BOOST_CHECK_EQUAL("LB/NA12878:Solexa-135852", mutation_stats.dnl);
Yes, this is easy in ReadGroup. But are we sure about this?
In read_group.h we got
Change everything to SAMPLE/LIBRARY, include both input and output
Need to match the last `/`, e.g. SM/1/Lib

2016-10-13 06:07 UTC, stevenhwu commented on src/lib/relationship_graph.cc
> +#define DNG_LB_PREFIX "LB/"
Option 1: If we must use #define, then I suggest create a `constant.h` file.
Option 2: If we don't need to use #define, how about `extern const std::string .....` in *.h

2016-10-13 06:40 UTC, stevenhwu commented
Accidentally push `e2b3b15`, ignore this commit

2016-10-13 17:55 UTC, reedacartwright commented on src/lib/relationship_graph.cc
> +#define DNG_LB_PREFIX "LB/"
Using a define allows the compiler to optimize the strings better as "a" "b" becomes "ab":

> String literals placed side-by-side are concatenated at translation phase 6 (after the preprocessor). That is, "Hello,"  " world!" yields the (single) string "Hello, world!". If the two strings have the same encoding prefix (or neither has one), the resulting string will have the same encoding prefix (or no prefix).

http://en.cppreference.com/w/cpp/language/string_literal

2016-10-28 22:27 UTC, stevenhwu commented on Tests/Unit/dng/find_mutation.cc
> +    BOOST_CHECK_EQUAL("LB/NA12878:Solexa-135852", mutation_stats.dnl);
Done.

2016-10-28 22:27 UTC, stevenhwu commented on src/include/dng/io/ped.h
> +    std::size_t id(const std::string &name, NameContainer &names) const {
Done.

2016-10-28 22:27 UTC, stevenhwu commented on src/include/dng/io/ped.h
> +        bool is_individual_id_not_unique = false;
Add TODO(RC): ****

2016-10-28 22:28 UTC, stevenhwu commented on src/lib/newick.cc
> +#define DNG_SM_PREFIX "SM/" // define also in relationship_graph.cc
Introduce constant.h

2016-10-28 23:03 UTC, stevenhwu reviewed
Address all requested changes.
Where will this message show up?
Rather useless here.....

2016-10-28 23:07 UTC, stevenhwu reviewed
Reply all comments in "review". 
Is this helpful?

2016-10-28 23:07 UTC, stevenhwu commented on Tests/Unit/dng/find_mutation.cc
> +    BOOST_CHECK_EQUAL("LB/NA12878:Solexa-135852", mutation_stats.dnl);
Done (reply in review).

2016-10-28 23:07 UTC, stevenhwu commented on src/include/dng/io/ped.h
> +    std::size_t id(const std::string &name, NameContainer &names) const {
Done (reply in review).

2016-10-28 23:07 UTC, stevenhwu commented on src/include/dng/io/ped.h
> +        bool is_individual_id_not_unique = false;
Add TODO(RC): ****   
(add to review)

2016-10-28 23:07 UTC, stevenhwu commented on src/include/dng/io/ped.h
> +                    ParseGender(string_table[nrow][4]),
Done (reply in review).

2016-10-28 23:07 UTC, stevenhwu commented on src/lib/newick.cc
> +#define DNG_SM_PREFIX "SM/" // define also in relationship_graph.cc
Introduce constant.h (add review)

2017-06-16 22:54 UTC, reedacartwright commented
Fixed in #220.

2017-06-16 22:54 UTC, closed without merging